import React, {useEffect, useState} from 'react'
import Head from 'next/head'
import Image from "next/image"
import {useRouter} from 'next/router'

import {apiEndpoint} from "../../config/configData.json"
import http from "../../service/http"

import * as date from "../../utils/date"
import MainCard from "../../components/MainCard"
import Card from "../../components/Card"
import LastNews from '../../components/LastNews'
import Match from '../../components/Match'

import styles from "../../styles/League.module.css"
import Players from '../../components/Players'

function League() {
  const router = useRouter()
  const {id} = router.query 
  const [team , setTeam] = useState([])
  const [matches , setMatches] = useState([])
  const [results , setResults] = useState([])
  const [selectedItem , setSelectedItem] = useState("news")

  useEffect(()=> {
    if(id){

        http.get(apiEndpoint + "/teams/" + id)
        .then((res) => {
            setTeam(res.data)
            console.log("team : " ,res.data)
        })
        .catch(error => {
            console.error(error)
        })
    
        http.get(apiEndpoint + "/getTeamMatches/" + id + "/" +date.generateTodayDate())
            .then((res) => {
                setMatches(res.data)
                console.log(res.data)
            })
            .catch(error => {
                console.error(error)
            })
            
        http.get(apiEndpoint + "/getTeamResult/" + id + "/" +date.generateTodayDate())
        .then((res) => {
            setResults(res.data.reverse())
            console.log(res.data)
        })
        .catch(error => {
            console.error(error)
        })
    }

  } , [id])

  const handleSelection = (target) => {
    setSelectedItem(target)
  }

  return (
    <div className={styles.container}>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />

            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
            <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@300;400;500;600;700;800&display=swap" rel="stylesheet" />
            <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet" />

        </Head>
        <div className={styles.wrapper}>
            <div className={styles.title + " " + styles.teamTitle}>
                {   
                    team.Logo &&
                    <Image
                        src = { team.Logo }
                        width = "30"
                        height = "30"
                    />
                }
                {team.Name}
            </div>
            <div className={styles.sections}>
                <div onClick={() => handleSelection("news")} style = {{background: selectedItem === "news" ? "rgb(var(--clr-grey))" : ""   }}>
                    الأخبار
                </div>
                <div onClick={() => handleSelection("matches")} style = {{background: selectedItem === "matches" ? "rgb(var(--clr-grey))" : ""   }}>
                    المباريات
                </div>
                <div onClick={() => handleSelection("results")} style = {{background: selectedItem === "results" ? "rgb(var(--clr-grey))" : ""   }}>
                    النتائج
                </div>
                <div onClick={() => handleSelection("squad")} style = {{background: selectedItem === "squad" ? "rgb(var(--clr-grey))" : ""   }}>
                    القائمة
                </div>
                <div onClick={() => handleSelection("other1")} style = {{background: selectedItem === "other1" ? "rgb(var(--clr-grey))" : ""   }}>
                    الإنتقالات
                </div>
                <div onClick={() => handleSelection("other2")} style = {{background: selectedItem === "other2" ? "rgb(var(--clr-grey))" : ""   }}>
                    الفيديو
                </div>
            </div>
            {   selectedItem === "news" ?
                <div className={styles.main}>
                    <div className={styles.maincard}>
                        <MainCard image = "/images/salah.jpg" />
                        <LastNews />
                    </div>
                    <div className={styles.cards}>
                        <Card image = "/images/salah.jpg" />
                        <Card image = "/images/salah.jpg" />
                        <Card image = "/images/salah.jpg" />
                        <Card image = "/images/salah.jpg" />
                        <Card image = "/images/salah.jpg" />
                        <Card image = "/images/salah.jpg" />
                    </div>
                </div>
                : selectedItem === "matches"
                ?                 
                matches.map((elm,index) => {
                    return(
                        <Match 
                            key={index}
                            type = "B"
                            league = {elm.Matches[0].League}
                            matches = {elm.Matches}
                        />
                    )
                })
                : selectedItem === "results"
                ?  
                results.map((elm,index) => {
                    return(
                        <Match 
                            key={index}
                            type = "B"
                            league = {elm.Matches[0].League}
                            matches = {elm.Matches}
                        />
                    )
                })
                : selectedItem === "squad"
                ?  
                <Players
                    data = {team.Players}
                />
                :  <div className={styles.main}>
                        <div className={styles.maincard}>
                            <MainCard image = "/images/salah.jpg" />
                            <LastNews />
                        </div>
                        <div className={styles.cards}>
                            <Card image = "/images/salah.jpg" />
                            <Card image = "/images/salah.jpg" />
                            <Card image = "/images/salah.jpg" />
                            <Card image = "/images/salah.jpg" />
                            <Card image = "/images/salah.jpg" />
                            <Card image = "/images/salah.jpg" />
                        </div>
                    </div>
            }

        </div>
    </div>
  )
}

export default League