import React,{useState,useEffect} from 'react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useSelector,useDispatch } from 'react-redux'

import * as date from "../../utils/date"
import {getMatches} from "../../store/matches"
import Match from '../../components/Match'
import styles from "../../styles/matches.module.css"
import Link from 'next/link'

function Matches() {
  const router = useRouter()
  const {id} = router.query
  const dispatch = useDispatch()
  const {data} = useSelector(state => state.matches)
  const [selectedItem, setSelectedItem] = useState("اليوم")

  const handleSelection = (target) => {
    setSelectedItem(target)
  }

  // const [count,setCout] = useState(0)

  // useEffect(() => {
  //     if(id)
  //       dispatch(getMatches(id))
  // } , [])

  useEffect(() => {
    if(id)
      dispatch(getMatches(id))  
  }, [id])

  return (
    <div className={styles.container}>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />

            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
            <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@300;400;500;600;700;800&display=swap" rel="stylesheet" />
            <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet" />
        </Head>

        <div className={styles.sections}>
          <Link  href={date.generateTodayDate()}>
            <div onClick={() => handleSelection("اليوم")} style = {{background: selectedItem === "اليوم" ? "rgb(var(--clr-grey))" : "" }}>
                اليوم
            </div>
          </Link>

          <Link href={date.generateYesterdayDate()}>
            <div onClick={() => handleSelection("أمس")} style = {{background: selectedItem === "أمس" ? "rgb(var(--clr-grey))" : "" }}>
                أمس
            </div>
          </Link>

          <Link href={date.generateTomorrowDate()}>
            <div onClick={() => handleSelection("الغد")} style = {{background: selectedItem === "الغد" ? "rgb(var(--clr-grey))" : "" }}>
                الغد
            </div>
          </Link>
        </div>

        <div className={styles.wrapper}>
          { data && 
            data.map((elm,index) => {
              return(
                <Match 
                    key={index}
                    type = "A"
                    league = {elm.League}
                    matches = {elm.Stages[0].Matches}
                />
              )
            })
          }
        </div>
    </div>
  )
}

export default Matches