# Generated by Django 3.2.8 on 2022-04-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='ab',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
