# Generated by Django 3.2.8 on 2022-04-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tag_ab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='ab',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
